### ISSUE TITLE
GitHub icon is from Sentry

### ISSUE THREAD

**Issue by w01fgang** [NaturalIntelligence/ThankYouBackers#1]
I'm not sure if it was done on purpose, but I think it's incorrect 😄 
<img width="375" alt="Screenshot 2024-01-05 at 11 25 29" src="https://github.com/NaturalIntelligence/ThankYouBackers/assets/8686751/41143cc7-81ec-4a6c-bc6f-2396ce8aa8b8">

**Comment by amitguptagwl** [comment]
Well, I meant 2 different entries. But it seems confusing. I'll correct it.
